import { keyMirror } from '@gilbarbara/helpers';

import { Status } from 'types';

export const ActionTypes = keyMirror({
  GITHUB_GET_REPOS_REQUEST: undefined,
  GITHUB_GET_REPOS_SUCCESS: undefined,
  GITHUB_GET_REPOS_FAILURE: undefined,
  HIDE_ALERT: undefined,
  SHOW_ALERT: undefined,
  SET_APP_OPTIONS: undefined,
  USER_LOGIN_REQUEST: undefined,
  USER_LOGIN_SUCCESS: undefined,
  USER_LOGIN_FAILURE: undefined,
  USER_LOGOUT_REQUEST: undefined,
  USER_LOGOUT_SUCCESS: undefined,
  USER_LOGOUT_FAILURE: undefined,
  USER_GET_LOGGINED_USER_INFO: undefined,
  RESERVATION_SEARCH: undefined,
  RESERVATION_SEARCH_FINISH: undefined,
  RESERVATION_CREATE: undefined,
  RESERVATION_CREATE_SUCCESS: undefined,
  RESERVATION_CREATE_FAILURE: undefined,
  RESERVATION_UPDATE: undefined,
  RESERVATION_UPDATE_SUCCESS: undefined,
  RESERVATION_UPDATE_FAILURE: undefined,
  RESERVATION_GET: undefined,
  RESERVATION_GET_FINISH: undefined,
  RESERVATION_RESET: undefined,
  RESERVATION_GET_DETAIL: undefined,
  RESERVATION_GET_DETAIL_FINISH: undefined,
  RESERVATION_GET_DETAIL_RESET: undefined,
  RESERVATION_NUMBER_GET: undefined,
  RESERVATION_NUMBER_GET_FINISH: undefined,
  ROOM_SEARCH: undefined,
  ROOM_SEARCH_FINISH: undefined,
  ROOM_SEARCH_RESET: undefined,
  ROOM_TYPE_GET: undefined,
  ROOM_TYPE_GET_FINISH: undefined,
  PRODUCT_SEARCH: undefined,
  PRODUCT_SEARCH_FINISH: undefined,
  AGENT_INFOS_GET: undefined,
  AGENT_INFOS_GET_FINISH: undefined,
});

export const STATUS: Status = {
  IDLE: 'idle',
  RUNNING: 'running',
  READY: 'ready',
  SUCCESS: 'success',
  ERROR: 'error',
};
